import type { Gang } from "../core/types.mts";

// Demonstração independente dos territórios, população e dinheiro do save.
// Data de registro desta configuração; não é relógio ou simulação offline.
const CREATED_AT = "2026-10-08T00:00:00.000Z";

export const INITIAL_GANGS: readonly Readonly<Gang>[] = Object.freeze([
  Object.freeze({
    id: "grove-street",
    name: "Grove Street Families",
    color: "#228B22" as const,
    members: 24,
    bankBalance: 85_000,
    territoryCount: 5,
    gangZoneCount: 2,
    baseCount: 1,
    wins: 3,
    losses: 1,
    aggressiveness: 55,
    skillLevel: 70,
    isPlayerGang: true,
    createdAt: CREATED_AT,
  }),
  Object.freeze({
    id: "ballas",
    name: "Ballas",
    color: "#800080" as const,
    members: 32,
    bankBalance: 160_000,
    territoryCount: 7,
    gangZoneCount: 3,
    baseCount: 1,
    wins: 4,
    losses: 2,
    aggressiveness: 80,
    skillLevel: 65,
    isPlayerGang: false,
    createdAt: CREATED_AT,
  }),
  Object.freeze({
    id: "los-vagos",
    name: "Los Santos Vagos",
    color: "#FFD700" as const,
    members: 28,
    bankBalance: 55_000,
    territoryCount: 4,
    gangZoneCount: 2,
    baseCount: 2,
    wins: 2,
    losses: 3,
    aggressiveness: 70,
    skillLevel: 60,
    isPlayerGang: false,
    createdAt: CREATED_AT,
  }),
  Object.freeze({
    id: "aztecas",
    name: "Varrios Los Aztecas",
    color: "#00BFFF" as const,
    members: 16,
    bankBalance: 25_000,
    territoryCount: 2,
    gangZoneCount: 1,
    baseCount: 1,
    wins: 1,
    losses: 2,
    aggressiveness: 40,
    skillLevel: 75,
    isPlayerGang: false,
    createdAt: CREATED_AT,
  }),
]);
